version: '3'
volumes:
  siwapp_gem_cache:
  siwapp_db_data:
    driver: local
  siwapp_node_modules:
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -b '0.0.0.0'
    depends_on:
      - db
    image: siwapp/siwapp
    networks:
      - my-network
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - siwapp_gem_cache:/usr/local/bundle/gems
      - siwapp_node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development
    stdin_open: true
    tty: true
  db:
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    image: postgres:9.6-alpine
    volumes:
      - siwapp_db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - my-network
networks:
  my-network:
    driver: bridge